# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

# AWS service name.
service: REST-API

custom:
  devicesTableName: Devices
  devicesTableArn: # ARNs are addresses of deployed services in AWS space.
    Fn::Join:
    - ":"
    - - arn
      - aws
      - dynamodb
      - Ref: AWS::Region
      - Ref: AWS::AccountId
      - table/${self:custom.devicesTableName}

provider:
  name: aws
  runtime: go1.x
  stage: api # Your development stage
  region: us-east-1
  environment:
    DEVICES_TABLE_NAME: ${self:custom.devicesTableName}
  iamRoleStatements: # Defines what other AWS services our lambda functions can access.        
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource:
        - "*"

package:
 individually: true


functions:
  devices:
    handler: devices
    package:
        artifact: bin/devices.zip
    events:
      - http:
          path: devices
          method: post
      - http:
          path: devices/{id}
          method: get
          
resources:
  Resources:
    DevicesTable: # Define a new DynamoDB Table resource to store items
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.devicesTableName}
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        AttributeDefinitions:
          - AttributeName: ID
            AttributeType: S
        KeySchema:
          - AttributeName: ID
            KeyType: HASH
